name: "Terraform-Plan-Infra-Plan"
on:
  push:
    branches:
      - FeatureBranch
      - main

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    env:	
      AWS_ACCESS_KEY_ID: "3hrir48nkd"
      AWS_SECRET_ACCESS_KEY: "dnffjfjr4kdm"
      AWS_REGION: 'us-east-1'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        id: init
        run: terraform init

      #- name: Terraform Init
      #  id: init
      #  run: terraform init